### ISSUE TITLE
There's something wrong with the result

### ISSUE THREAD

**Issue by Chengyang852** [adobe-research/convmelspec#8]
Thank you for your work. I encountered some problems while using this library.
![image](https://github.com/adobe-research/convmelspec/assets/81755002/25d4bb53-07a8-4fbc-818b-e4e7c9ba3fbd)
Is there something wrong with my use?

**Comment by urinieto** [comment]
Could you `pip install coremltools` in a fresh environment? If that doesn't work, maybe this is not supported on Windows? (Seems like you're developing on a Windows box)

**Comment by urinieto** [comment]
I'll close this for now. Please @Chengyang852 let us know if you managed to fix it.

**Comment by urinieto** [comment]
Oh, just realized I don't have permissions to close this. Maybe @njb can help?

**Comment by njb** [comment]
@urinieto I updated your permissions, thank you for addressing

**Comment by urinieto** [comment]
Great, thanks! Closing this for now.
